---
conditions:
  all:
    - fact: payload.action
      operator: equal
      value: created
    - fact: payload.issue.id
      operator: notEmpty
      value: ''

event:
  type: issueTalk
  params:
    data: "Let's play by the Rules. This is a Server Rule! "
# default is '1'
priority: 1
